  const BUDGET_COPY = {
    "budget.documentTitle": ["Hbit - Budget", "Hbit - Budget"],
    "budget.hero.leftToSpend": ["Left to spend", "Reste a depenser"],
    "budget.hero.spentThisMonth": ["Spent this month", "Depense ce mois-ci"],
    "budget.hero.ofBudgeted": ["of {amount} budgeted", "sur {amount} prevus"],
    "budget.hero.noBudget": ["Set a plan to track budget usage.", "Cree un plan pour suivre ton budget."],
    "budget.status.checking": ["Checking", "Verification"],
    "budget.status.setup": ["No budget set", "Aucun budget defini"],
    "budget.status.over": ["Over budget", "Budget depasse"],
    "budget.status.close": ["Close watch", "A surveiller"],
    "budget.status.onTrack": ["On track", "Sur la bonne voie"],
    "budget.streak.dayLabel": ["Day", "Jour"],
    "budget.quick.expense": ["Expense", "Depense"],
    "budget.quick.income": ["Income", "Revenu"],
    "budget.quick.bill": ["Bill", "Facture"],
    "budget.quick.account": ["Account", "Compte"],
    "budget.quick.goal": ["Goal", "Objectif"],
    "budget.health.title": ["Financial Health", "Sante financiere"],
    "budget.health.details": ["Details", "Details"],
    "budget.health.excellent": ["Excellent", "Excellent"],
    "budget.health.good": ["Good", "Bon"],
    "budget.health.fair": ["Fair", "Moyen"],
    "budget.health.poor": ["Poor", "Fragile"],
    "budget.health.savingsRate": ["Savings rate", "Taux d'epargne"],
    "budget.health.adherence": ["Budget adherence", "Respect du budget"],
    "budget.health.goalSet": ["Savings goal set", "Objectif d'epargne actif"],
    "budget.planner.autofill": ["Auto-fill 50/30/20", "Remplir 50/30/20"],
    "budget.planner.autofillApply": ["Apply Plan", "Appliquer le plan"],
    "budget.planner.autofillNoIncome": ["Log your income first to use this feature.", "Ajoute d'abord ton revenu pour utiliser cette fonction."],
    "budget.planner.autofillBased": ["Based on your income of", "Base sur ton revenu de"],
    "budget.planner.autofillApplied": ["50/30/20 plan applied.", "Plan 50/30/20 applique."],
    "budget.planner.needs": ["Needs", "Besoins"],
    "budget.planner.wants": ["Wants", "Envies"],
    "budget.planner.savings": ["Savings", "Epargne"],
    "budget.bills.all": ["All", "Tout"],
    "budget.bills.unpaidTab": ["Unpaid", "Non payees"],
    "budget.bills.subscriptions": ["Subscriptions", "Abonnements"],
    "budget.bills.dueSoon": ["Due soon", "Bientot due"],
    "budget.bills.overdue": ["Overdue", "En retard"],
    "budget.bills.upcoming": ["Upcoming", "A venir"],
    "budget.flow.billCatLead": ["Choose a bill category", "Choisis une categorie de facture"],
    "budget.flow.billAmountLead": ["How much is this bill?", "Quel est le montant?"],
    "budget.flow.billDetailsLead": ["Bill details", "Details de la facture"],
    "budget.import.label": ["Attach receipt or statement", "Joindre un recu ou releve"],
    "budget.import.mobile": ["Mobile", "Mobile"],
    "budget.export.pdfTitle": ["PDF report", "Rapport PDF"],
    "budget.export.pdfBtn": ["Download PDF Report", "Telecharger le rapport PDF"],
    "budget.monthend.saved": ["You saved", "Tu as economise"],
    "budget.monthend.net": ["Net result", "Resultat net"],
    "budget.monthend.income": ["Income", "Revenu"],
    "budget.monthend.spent": ["Spent", "Depense"],
    "budget.monthend.bills": ["Bills paid", "Factures payees"],
    "budget.monthend.vsLast": ["Vs last month", "Vs mois dernier"],
    "budget.monthend.quoteGood": ["Small money choices added up nicely.", "Les petits choix ont fait une belle difference."],
    "budget.monthend.quoteTight": ["A tight month still teaches useful patterns.", "Un mois serre revele quand meme des tendances utiles."],
    "budget.monthend.share": ["Share", "Partager"],
    "budget.monthend.close": ["Done", "Termine"],

    /* KPI summary cards (also bound via data-bg-i18n="budget.income/spent/remaining") */
    "budget.income": ["Income", "Revenu"],
    "budget.spent": ["Spent", "Depense"],
    "budget.remaining": ["Remaining", "Restant"],
    "budget.kpi.income": ["Income", "Revenu"],
    "budget.kpi.spent": ["Spent", "Depense"],
    "budget.kpi.remaining": ["Remaining", "Restant"],

    /* Accounts */
    "budget.accounts.title": ["Accounts", "Comptes"],
    "budget.accounts.add": ["Add account", "Ajouter un compte"],
    "budget.accounts.addHint": ["Add your first account to track balances.", "Ajoute ton premier compte pour suivre les soldes."],
    "budget.accounts.salary": ["Salary", "Salaire"],
    "budget.accounts.cash": ["Cash", "Especes"],
    "budget.accounts.credit": ["Credit card", "Carte de credit"],
    "budget.accounts.debt": ["Debt", "Dette"],
    "budget.accounts.noRecent": ["No recent change", "Pas de changement recent"],
    "budget.accounts.edit": ["Edit account", "Modifier le compte"],
    "budget.accounts.emptyHint": ["No accounts yet. Add your first account to start tracking your budget.", "Aucun compte pour l'instant. Ajoute ton premier compte pour suivre ton budget."],

    /* Financial Health / networth */
    "budget.health.sub": ["Details", "Details"],
    "budget.networth": ["Net worth", "Valeur nette"],

    /* Money Overview donut legend */
    "budget.overview.title": ["Money Overview", "Apercu financier"],
    "budget.overview.income": ["Income", "Revenu"],
    "budget.overview.spent": ["Spent", "Depense"],
    "budget.overview.debt": ["Debt", "Dette"],
    "budget.overview.remaining": ["Remaining", "Restant"],

    /* Spending by category */
    "budget.pie.title": ["Spending by category", "Depenses par categorie"],
    "budget.pie.total": ["total", "total"],
    "budget.pie.empty": ["No expenses this month", "Aucune depense ce mois-ci"],

    /* Transactions */
    "budget.tx.title": ["Transactions", "Transactions"],
    "budget.tx.search": ["Search transactions...", "Rechercher une transaction..."],
    "budget.tx.all": ["All", "Tout"],
    "budget.tx.income": ["Income", "Revenu"],
    "budget.tx.expenses": ["Expenses", "Depenses"],
    "budget.tx.empty": ["No transactions yet", "Aucune transaction"],
    "budget.tx.emptySub": ["Log your first expense or income to get started.", "Enregistre une depense ou un revenu pour commencer."],
    "budget.tx.logExpense": ["+ Log an expense", "+ Ajouter une depense"],
    "budget.tx.defaultLabel": ["Transaction", "Transaction"],

    /* Savings Goals */
    "budget.goals.title": ["Savings Goals", "Objectifs d'epargne"],
    "budget.goals.emptyTitle": ["Create a savings goal to stay motivated", "Cree un objectif d'epargne pour rester motive"],
    "budget.goals.emptySub": ["Save for a vacation, emergency fund, or down payment.", "Epargne pour des vacances, un fonds d'urgence ou un acompte."],
    "budget.goals.set": ["Set a Goal", "Definir un objectif"],
    "budget.goals.new": ["+ New Goal", "+ Nouvel objectif"],
    "budget.goals.defaultName": ["Goal", "Objectif"],
    "budget.goals.savedOf": ["{saved} saved of {target}", "{saved} economises sur {target}"],
    "budget.goals.byDate": ["By {date}", "D'ici {date}"],
    "budget.goals.toStayOnTrack": ["+{amount} to stay on track", "+{amount} pour rester sur la bonne voie"],
    "budget.goals.pastDue": ["Past due", "En retard"],
    "budget.goals.onTrack": ["On track ✓", "Sur la bonne voie ✓"],
    "budget.goals.behind": ["Behind ⚠", "En retard ⚠"],
    "budget.goals.setMonthlyTarget": ["Set monthly target", "Definir une cible mensuelle"],

    /* Budget Planner */
    "budget.planner.title": ["Budget Planner", "Planification du budget"],
    "budget.planner.sub": ["Tap to set a monthly limit", "Touche pour definir une limite mensuelle"],
    "budget.planner.track": ["Track", "Suivre"],
    "budget.planner.plan": ["Plan", "Planifier"],
    "budget.planner.remaining": ["Remaining", "Restant"],
    "budget.planner.noLimit": ["No limit set", "Aucune limite"],
    "budget.planner.setLimit": ["Set limit", "Definir"],
    "budget.planner.overBudget": ["Over budget", "Hors budget"],
    "budget.planner.summary": ["Budgeted: {budgeted} - Spent: {spent} - Remaining: {remaining}", "Prevu: {budgeted} - Depense: {spent} - Restant: {remaining}"],

    /* Category names */
    "budget.cat.housing": ["Housing", "Logement"],
    "budget.cat.food": ["Food", "Alimentation"],
    "budget.cat.transport": ["Transport", "Transport"],
    "budget.cat.health": ["Health", "Sante"],
    "budget.cat.fun": ["Fun", "Loisirs"],
    "budget.cat.subscriptions": ["Subscriptions", "Abonnements"],
    "budget.cat.shopping": ["Shopping", "Achats"],
    "budget.cat.education": ["Education", "Education"],
    "budget.cat.savings": ["Savings", "Epargne"],
    "budget.cat.other": ["Other", "Autre"],

    /* Bills */
    "budget.bills.title": ["Bills", "Factures"],
    "budget.bills.add": ["Add bill", "Ajouter une facture"],
    "budget.bills.paid": ["Paid", "Payees"],
    "budget.bills.unpaid": ["Unpaid", "Non payees"],
    "budget.bills.empty": ["No bills yet", "Aucune facture"],
    "budget.bills.emptySub": ["Add recurring bills like rent, utilities or subscriptions.", "Ajoute des factures recurrentes : loyer, services, abonnements."],
    "budget.bills.emptyDebtTitle": ["Add bills to track minimum payments", "Ajoute tes factures pour suivre les paiements minimums"],
    "budget.bills.emptyDebtSub": ["Never miss a due date - critical for your debt payoff plan.", "Ne manque aucune echeance - essentiel pour ton plan de remboursement."],
    "budget.bills.statusPaid": ["Paid", "Payée"],
    "budget.bills.statusLate": ["Late", "En retard"],
    "budget.bills.statusDue": ["Due", "À venir"],
    "budget.bills.statusOverdue": ["Overdue", "En retard"],
    "budget.bills.statusDueSoon": ["Due soon", "Bientot due"],
    "budget.a11y.editRow": ["Edit", "Modifier"],

    /* Spending Activity */
    "budget.activity.title": ["Spending Activity", "Activite des depenses"],
    "budget.activity.daily": ["Daily spending", "Depenses quotidiennes"],
    "budget.activity.weekly": ["Weekly spending", "Depenses hebdomadaires"],

    /* Setup checklist */
    "budget.setup.title": ["Set up your budget", "Configure ton budget"],
    "budget.setup.sub": ["Complete these to unlock the full dashboard.", "Termine ces etapes pour debloquer tout le tableau de bord."],
    "budget.setup.count": ["{done} / {total} done", "{done} / {total} termine"],
    "budget.setup.logIncome": ["Log your first income", "Enregistre ton premier revenu"],
    "budget.setup.setPlan": ["Set your monthly plan", "Definis ton plan mensuel"],
    "budget.setup.logExpense": ["Log your first expense", "Enregistre ta premiere depense"],
    "budget.setup.addBill": ["Add a recurring bill", "Ajoute une facture recurrente"],
    "budget.setup.createGoal": ["Create a savings goal", "Cree un objectif d'epargne"],
    "budget.empty.goals.title": ["Create a savings goal to stay motivated", "Cree un objectif d'epargne pour rester motive"],
    "budget.empty.goals.sub": ["Save for a vacation, emergency fund, or down payment.", "Epargne pour des vacances, un fonds d'urgence ou un acompte."],
    "budget.empty.goals.cta": ["Set a Goal", "Definir un objectif"],
    "budget.empty.planner.title": ["Set budget limits to take control", "Definis des limites pour prendre le controle"],
    "budget.empty.planner.sub": ["Choose categories and set monthly targets.", "Choisis des categories et definis des cibles mensuelles."],
    "budget.empty.planner.cta": ["Create a budget", "Creer un budget"],
    "budget.empty.tx.title": ["Add your first transaction to start tracking", "Ajoute ta premiere transaction pour commencer le suivi"],
    "budget.empty.tx.sub": ["Track cash, transfers, or anything missing from your bank.", "Suis l'argent comptant, les transferts ou ce qui manque a ta banque."],

    /* Smart alerts */
    "budget.alert.overCategory": ["You've exceeded your {category} budget by {amount} this month.", "Tu as depasse ton budget {category} de {amount} ce mois-ci."],
    "budget.alert.incomeHint": ["Income uses Salary and Cash account balances. Add an account to set income.", "Le revenu utilise les soldes Salaire et Especes. Ajoute un compte pour definir ton revenu."],
    "budget.alert.dismiss": ["Dismiss alert", "Fermer l'alerte"],
    "budget.alert.setNow": ["Set it now", "Definir maintenant"],
    "budget.alert.startPlanning": ["Start planning", "Commencer la planification"],

    /* Add-expense modal */
    "budget.modal.addExpense": ["Add expense", "Ajouter une depense"],
    "budget.modal.addIncome": ["Add income", "Ajouter un revenu"],
    "budget.modal.addBill": ["Add a bill", "Ajouter une facture"],
    "budget.modal.addAccount": ["Add account", "Ajouter un compte"],
    "budget.modal.addGoal": ["Add savings goal", "Ajouter un objectif d'epargne"],
    "budget.modal.save": ["Save", "Enregistrer"],
    "budget.modal.cancel": ["Cancel", "Annuler"],

    /* Daily allowance chip */
    "budget.daily.leftToday": ["{amount} left today", "{amount} restant aujourd'hui"],
  };
